sistema_acesso_school:
    resource: "@SistemaAcessoSchoolBundle/Controller"
    type:     annotation
    prefix:   /

sistema_acesso_user:
    resource: "@SistemaAcessoUserBundle/Controller"
    type:     annotation
    prefix:   /

sistema_acesso_base:
    resource: "@SistemaAcessoBaseBundle/Controller"
    type:     annotation
    prefix:   /

sistema_acesso_access_control:
    resource: "@SistemaAcessoAccessControlBundle/Controller"
    type:     annotation
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

