sistema_acesso_user:
    resource: "@SistemaAcessoUserBundle/Controller"
    type:     annotation
    prefix:   /

sistema_acesso_base:
    resource: "@SistemaAcessoBaseBundle/Controller"
    type:     annotation
    prefix:   /

