services:
  status_label.twig_extension:
      class: SistemaAcesso\BaseBundle\TwigExtensions\StatusLabelExtension
      public: false
      tags:
          - { name: twig.extension }
  count.twig_extension:
      class: SistemaAcesso\BaseBundle\TwigExtensions\LabelCountElementExtension
      public: false
      tags:
          - { name: twig.extension }